### ISSUE TITLE
[v1.4] Turning off opacity in corePlugins config still generates CSS variables

### ISSUE THREAD

**Issue by pheuter** [tailwindcss/tailwindcss#1670]
The generated CSS file has increased substantially in size (~40%) as a result and I can't seem to turn it off.

**tailwind.config.js**
```js
corePlugins: {
    divideOpacity: false,
    backgroundOpacity: false,
    borderOpacity: false,
    placeholderOpacity: false,
    textOpacity: false
}
```

**Generated CSS**
```css
a {
  --text-opacity: 1;
  color: rgba(255, 128, 153, var(--text-opacity));
}

.divide-black > :not(template) ~ :not(template){
  --divide-opacity: 1;
  border-color: rgba(51, 51, 51, var(--divide-opacity));
}

.bg-black{
  --bg-opacity: 1;
  background-color: rgba(51, 51, 51, var(--bg-opacity));
}
```

**Comment by emptynick** [comment]
Same here.
Disabling the core-modules only removes the corresponding classes `.bg-opacity-*`, `.text-opacity-*` and so on.

**Comment by adamwathan** [comment]
I think we can improve this for sure by adding some API to the plugin system to allow checking if a given plugin is enabled. For now I'd recommend what @emptynick suggested and use the `ie11` target mode for the color plugins:

```js
target: ['relaxed', {
  backgroundColor: 'ie11',
  textColor: 'ie11',
  borderColor: 'ie11',
  placeholderColor: 'ie11',
  divideColor: 'ie11',
}]
```

**Comment by ryanfitzer** [comment]
Where is `target` documented? I'm not seeing it on the [Configuration](https://tailwindcss.com/docs/configuration) page.

**Comment by emptynick** [comment]
In the release notes and in [the PR](https://github.com/tailwindcss/tailwindcss/pull/1635). 
Its experimental and (I guess) therefore not yet documented

**Comment by ryanfitzer** [comment]
Question: for the `browserslist` target, I've tried the following approaches that all evaluate to [these browser versions](https://browserl.ist/?q=last+3+Chrome+major+versions%2C+last+3+Firefox+versions%2C+last+3+Edge+versions%2C+last+3+Safari+versions%2C+IE+11%2C+last+3+ChromeAndroid+versions%2C+last+3+iOS+versions), but I still get custom properties in the output:

1. `browserslist` key in `package.json`.
2. `.browserslistrc` config file.
3. `browserslist` config file.

The only thing that works is using `target: 'ie11'`. Is the `browserslist` target not in `1.4.1`?

**Comment by adamwathan** [comment]
Fixed in v1.4.3 👍

**Comment by adamwathan** [comment]
@ryanfitzer Crap good catch, it was only working using the tuple syntax (`['browserslist', {...}]`). I've just published a fix in v1.4.4 👍

**Comment by nunong21** [comment]
@adamwathan I was wondering if this fix still applies to version 2 of Tailwind. 
I was trying to use it in IE but the opacity variable is blocking my colors

**Comment by nunong21** [comment]
@adamwathan  Yes, I've read that and a lot more posts about it. 
Even tho IE should die, we still have a couple thousand that use our SAAS in old browser like IE8. 

After a couple tests the only thing that I didn't manage to get working was the colors, only for this reason. 
Even if I set in my config that I don't want to use opacity, I still end up with a variable on my RGBa. 

This is the problem of having to support IE unfortunately... 
I've been using Tailwind also on other projects and so far it's been great! Really well done!
