### ISSUE TITLE
border not working as per docs

### ISSUE THREAD

**Issue by SouthRibbleTech** [tailwindcss/tailwindcss#951]
It looks like so bug has made it's way in so that you can not specify a border for a specific side.

`border-b-2 border-blue-600` does not work.
`border-2 border-blue-600` does not work

`border-b-2 border-blue-600 border-solid` puts a border on all 4 sides.

**Comment by adamwathan** [comment]
Sounds like you are probably using `@tailwind preflight` instead of `@tailwind base`, switching that should fix your problem 👍 

https://tailwindcss.com/docs/upgrading-to-v1#4-replace-tailwind-preflight-with-tailwind-base

**Comment by adamwathan** [comment]
I've just published v1.0.3 which explicitly throws an error if you forget to update `preflight` to `base` so with any luck others will stop running into this one 👍

**Comment by adamwathan** [comment]
Would bet $10,000 that the `preflight`/`base` thing is the source of the issue so gonna close this, but if that doesn't fix it I'll re-open 👍

**Comment by benjiminio** [comment]
Borders still don't work for me. I'm using `@tailwind base`. Any idea?

**Comment by adamwathan** [comment]
Please create a GitHub repo that reproduces and I’m happy to help troubleshoot 👍🏻

**Comment by designbyadrian** [comment]
@benjiminio Did you resolve the issue? It's many months later and I just stumbled upon this issue.
